# Generated by Django 4.1.5 on 2023-01-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_aircon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=255)),
                ('customerAddress', models.CharField(max_length=255)),
                ('customerEmail', models.CharField(max_length=255)),
                ('customerPhone', models.CharField(max_length=255)),
                ('customerStatus', models.BooleanField()),
            ],
        ),
    ]
