# Generated by Django 4.1.5 on 2023-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_aircon', '0002_customer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='technician_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.CharField(max_length=255)),
                ('techPhone', models.CharField(max_length=255)),
                ('techEmail', models.CharField(max_length=255)),
                ('techSched', models.CharField(max_length=255)),
            ],
        ),
    ]
